name: CI/CD

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

env:
  REGISTRY: maximpr
  IMAGE_NAME: task-manager-api
  CONTAINER_NAME: task-manager-api

jobs:

  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Lint the project
        run: |
          pip install flake8
          flake8 .
  
  run-tests:
    runs-on: ubuntu-latest
    needs: run-linter

    services:
      test-db:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pip install pytest pytest-asyncio
          pytest tests/
      - name: Coverage
        run: |
          pytest --cov
